export const PRESETS=[
['original','Original painting','#747571','#4d382e','#ac7c3e',0],
['cold-steel','Cold steel','#7f929e','#392f31','#a9a8a1',85],
['oxblood','Oxblood & iron','#595d64','#742a32','#928274',90],
['bronze','Ancient bronze','#a17b45','#43382c','#b49458',90],
['violet','Amethyst','#79688f','#332e38','#a29178',85],
['bone','Ivory & brass','#c4b698','#51402e','#a17a43',90],
['jade','Jade','#5e8873','#373b32','#b69353',90],
['ember','Ember','#985349','#45262a','#ba8849',90]];
export function recipeFor(a,p=PRESETS[0]){return {version:1,asset:a.id,prefix:'none',layers:Object.fromEntries(a.regions.map((r,i)=>[r,{color:p[i+2],strength:p[5]}])),background:'#918572',transparent:true};}
export function validate(r,assets){const a=assets.find(a=>a.id===r?.asset);if(!a||r.version!==1)throw Error('Unknown item or recipe version.');for(const k of a.regions)if(!/^#[0-9a-f]{6}$/i.test(r.layers?.[k]?.color)||!Number.isFinite(r.layers[k].strength)||r.layers[k].strength<0||r.layers[k].strength>100)throw Error('Invalid material color or strength.');if(!/^#[0-9a-f]{6}$/i.test(r.background))throw Error('Invalid background.');const prefix=r.prefix||'none';if(!['none','flaming','poisonous','charged','enchanted','blessed'].includes(prefix)||(!a.supportsPrefixes&&prefix!=='none'))throw Error('Invalid prefix for this item.');return {...r,prefix};}
export function tint(base,mask,r,a){const out=new Uint8ClampedArray(base);for(let p=0;p<out.length;p+=4){if(!base[p+3]||!(mask[p]||mask[p+1]||mask[p+2]))continue;const i=mask[p]>=mask[p+1]&&mask[p]>=mask[p+2]?0:mask[p+1]>=mask[p+2]?1:2,l=r.layers[a.regions[i]],amount=l.strength/100,lum=.2126*base[p]+.7152*base[p+1]+.0722*base[p+2],anchor=a.referenceLuma[i];for(let c=0;c<3;c++){const color=parseInt(l.color.slice(1+c*2,3+c*2),16),v=lum<=anchor?color*lum/anchor:color+(255-color)*(lum-anchor)/(255-anchor);out[p+c]=Math.round(base[p+c]*(1-amount)+v*amount);}}return out;}
export function relief(base,map){const out=new Uint8ClampedArray(base),palette=[0,0,0];let n=0;for(let p=0;p<base.length;p+=4)if(map[p+3]&&base[p+3]){n++;for(let c=0;c<3;c++)palette[c]+=base[p+c];}if(!n)return out;for(let c=0;c<3;c++)palette[c]/=n;for(let p=0;p<out.length;p+=4)if(map[p+3]&&base[p+3])for(let c=0;c<3;c++){const v=map[p],color=palette[c],lit=v<128?color*v/128:color+(255-color)*(v-128)/127;out[p+c]=base[p+c]+(lit-base[p+c])*map[p+3]/255;}return out;}
export function isolate(base,mask,index){const out=new Uint8ClampedArray(base);for(let p=0;p<out.length;p+=4){const fixed=!(mask[p]||mask[p+1]||mask[p+2]);out[p+3]=index===0&&fixed?out[p+3]:Math.round(out[p+3]*mask[p+index]/255);}return out;}
export async function zip(files){const parts=[],central=[];let offset=0;const enc=new TextEncoder();let count=0;for(const [name,value] of Object.entries(files)){const bytes=value instanceof Blob?new Uint8Array(await value.arrayBuffer()):enc.encode(value),nm=enc.encode(name);let crc=0xffffffff;for(const b of bytes){crc^=b;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;const h=new Uint8Array(30+nm.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,nm.length,true);h.set(nm,30);parts.push(h,bytes);const ch=new Uint8Array(46+nm.length),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,crc,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,nm.length,true);cv.setUint32(42,offset,true);ch.set(nm,46);central.push(ch);offset+=h.length+bytes.length;count++;}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,count,true);v.setUint16(10,count,true);v.setUint32(12,central.reduce((s,x)=>s+x.length,0),true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'});}
