using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace RPGGame.UI.Avalonia.Settings
{
    public partial class TextDelaysSettingsPanel : UserControl
    {
        // Note: All control properties are auto-generated by Avalonia from x:Name attributes in the AXAML file
        // No need to manually define them with FindControl
        
        public TextDelaysSettingsPanel()
        {
            InitializeComponent();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}

