using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Layout;
using Avalonia.Threading;
using RPGGame;
using RPGGame.UI.Avalonia.Helpers;
using RPGGame.Utils;
using System;
using System.ComponentModel;
using System.Text.Json;

namespace RPGGame.UI.Avalonia
{
    public partial class SettingsWindow : Window
    {
        private GameCoordinator? gameCoordinator;
        private CanvasUICoordinator? canvasUI;
        private GameStateManager? gameStateManager;
        private System.Action<string>? updateStatus;
        private bool _firstLayoutLogged = false; // Track first layout update
        private SettingsPanel? SettingsMenuPanel; // Created dynamically after window is shown
        // MainGrid is auto-generated by Avalonia from XAML

        public SettingsWindow()
        {
            InitializeComponent();
            
            // SettingsPanel is NOT in visual tree initially - will be added after Show() completes
            // This prevents Avalonia from measuring/arranging the 2563-line panel during Show()
            SettingsMenuPanel = null;
            
            // Use default activation behavior - window will activate when shown
            
            // Handle window closing to restore game state
            this.Closing += OnWindowClosing;
            
            // Handle Escape key to close window
            this.KeyDown += OnKeyDown;
            
            // Instrumentation: Track when window becomes responsive
            this.Loaded += (s, e) =>
            {
            };
            
            // Instrumentation: Track first render
            this.LayoutUpdated += (s, e) =>
            {
                // Only log first layout update
                if (!_firstLayoutLogged)
                {
                    _firstLayoutLogged = true;
                }
            };
        }

        /// <summary>
        /// Initializes the settings window with game references
        /// </summary>
        public void Initialize(
            GameCoordinator? game,
            CanvasUICoordinator? ui,
            GameStateManager? stateManager,
            System.Action<string>? statusCallback)
        {
            gameCoordinator = game;
            canvasUI = ui;
            gameStateManager = stateManager;
            updateStatus = statusCallback;

            // Initialize the settings panel after window is shown
            // SettingsPanel is hidden initially to prevent blocking layout pass during Show()
            // We show it after the window is displayed to avoid the 3-second freeze
            this.Opened += async (s, e) =>
            {
                // Small delay to ensure window is fully rendered and interactive
                await Task.Delay(50);
                
                // Defer panel creation with SystemIdle priority to ensure window is fully interactive first
                Dispatcher.UIThread.Post(() =>
                {
                    // Create and add SettingsPanel to visual tree AFTER window is displayed and interactive
                    // This prevents Avalonia from measuring/arranging the 2563-line panel during Show()
                    if (SettingsMenuPanel == null && MainGrid != null)
                    {
                        SettingsMenuPanel = new SettingsPanel();
                        SettingsMenuPanel.HorizontalAlignment = HorizontalAlignment.Stretch;
                        SettingsMenuPanel.VerticalAlignment = VerticalAlignment.Stretch;
                        SettingsMenuPanel.Margin = new Thickness(0);
                        MainGrid.Children.Add(SettingsMenuPanel);
                    }
                    
                    // Set up callbacks for back button and status updates
                    if (SettingsMenuPanel != null)
                    {
                        SettingsMenuPanel.SetBackCallback(() =>
                        {
                            Close();
                        });
                        
                        SettingsMenuPanel.SetStatusCallback((message) =>
                        {
                            updateStatus?.Invoke(message);
                        });
                        
                        // Initialize handlers for developer tools after window is visible and interactive
                        SettingsMenuPanel.InitializeHandlers(
                            gameCoordinator?.DeveloperMenuHandler,
                            gameCoordinator,
                            canvasUI,
                            gameStateManager);
                    }
                }, DispatcherPriority.SystemIdle);
            };
        }

        /// <summary>
        /// Handles window closing - doesn't affect main window state
        /// </summary>
        private void OnWindowClosing(object? sender, CancelEventArgs e)
        {
            // Don't change game state - main window should continue functioning normally
            // The settings window is independent and doesn't affect the main window
            // No need to restore rendering since we never suppressed it
        }

        /// <summary>
        /// Handles keyboard input (Escape key to close)
        /// </summary>
        private void OnKeyDown(object? sender, KeyEventArgs e)
        {
            if (e.Key == Key.Escape)
            {
                Close();
                e.Handled = true;
            }
        }
    }
}

