import {readFile,writeFile} from 'node:fs/promises';
const rows=[];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');
function shape(name,family,tier){
 const n=name.toLowerCase();
 if(family==='mace')return /flail/.test(n)?'flail':/hammer|mallet|maul|tombstone/.test(n)?'hammer':/morningstar/.test(n)?'morningstar':tier===1?'club':'mace';
 if(family==='sword')return /scythe|reaper/.test(n)?'scythe':/glaive|halbr/.test(n)?'polearm':/cleav|chop|split/.test(n)?'cleaver':/saber|scimitar|cutlass|falchion|kukri/.test(n)?'saber':/rapier|foil|stiletto/.test(n)?'rapier':'sword';
 if(family==='dagger')return /kris/.test(n)?'kris':/hook|claw/.test(n)?'hook':/fang|thorn/.test(n)?'fang':'dagger';
 if(family==='wand'){
  if(/tome|grimoire|covenant/.test(n))return 'book';
  if(/scroll|binding/.test(n))return 'scroll';
  if(/lantern|candle/.test(n))return 'lantern';
  if(/cauldron|vessel|vial/.test(n))return 'vessel';
  if(/skull|head|effigy|idol|totem/.test(n))return 'idol';
  if(/monolith|obelisk|pillar|altar/.test(n))return 'obelisk';
  if(/crystal|shard|geode|prism/.test(n))return 'crystal';
  if(/orb|lens|essence|seed|axiom|convergence|catalyst/.test(n))return 'orb';
  if(/charm|bead|sigil|rune|gylgh|talis|tails|trinket|compass|relic|artifact|cradle/.test(n))return 'amulet';
  return /staff|stick|branch/.test(n)?'staff':'wand';
 }
 if(family==='head')return /crown|circlet|band|headdress/.test(n)?'crown':/hood|cowl|veil|wrap|kerf|scrap/.test(n)?'hood':/cap|hat|toque/.test(n)?'cap':/mask|face|jaw|visor/.test(n)?'mask':'helmet';
 if(family==='chest')return /mail/.test(n)?'mail':/coat|jacket|mantle|tabard|surcoat|wrap/.test(n)?'coat':/vest|shirt|jerkin/.test(n)?'tunic':'chestplate';
 if(family==='legs')return /breech|trouser|legging|wrap/.test(n)?'trousers':'greaves';
 if(family==='feet')return /sandal|slipper|shoe|brogue|sneaker|mocc/.test(n)?'shoes':'boots';
 if(family==='charm')return 'amulet';
 return /apple/.test(n)?'apple':/bread|ration/.test(n)?'bread':/cheese/.test(n)?'cheese':/jerky|sausage/.test(n)?'ration':'potion';
}
for(const source of ['Weapons','Armor','Charms','Consumables']){
 const data=JSON.parse(await readFile(new URL(`../../GameData/${source}.json`,import.meta.url),'utf8'));
 const counts={};
 for(const row of data){
  const name=row.name||row.displayName;if(!name)continue;
  const family=source==='Weapons'?row.type.toLowerCase():source==='Armor'?row.slot:source==='Charms'?'charm':'consumable';
  const tier=row.tier||1,key=`${family}-${slug(name)}-t${tier}`,ordinal=counts[key]=(counts[key]||0)+1;
  rows.push({id:key+(ordinal>1?`-${ordinal}`:''),name,family,tier:row.tier||null,rarity:row.rarity||null,shape:shape(name,family,tier),source,affixable:source!=='Consumables',effect:row.effect||null});
 }
}
await writeFile(new URL('./item-catalog.js',import.meta.url),'// Generated by node tools/weapon-forge/sync-items.mjs from the four GameData item catalogs.\nexport const ITEM_CATALOG = '+JSON.stringify(rows,null,2)+';\n');
console.log(`${rows.length} entries, ${new Set(rows.map(r=>r.shape)).size} reusable silhouettes`);
